### ISSUE TITLE
Build/execution instructions should specify building and running optimized versions

### ISSUE THREAD

**Issue by tikue** [google/hat-backup#3]
`cargo build` builds a debug version; prefer `cargo build --release` instead for an optimized build. Same with `cargo run`, which runs the debug version, versus `cargo run --release`, which runs the optimized version.

**Comment by brinchj** [comment]
Not sure why I went with plain "cargo build/run" in those instructions. I've changed it to add "--release" as the code is very slow without it. 

Thanks for the heads up :+1:
